"""empty message

Revision ID: 64aa2e5f0745
Revises: 162651cf40c0
Create Date: 2022-09-14 17:49:52.067349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64aa2e5f0745'
down_revision = '162651cf40c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
