"""empty message

Revision ID: 142957a40c0b
Revises: 64aa2e5f0745
Create Date: 2022-09-15 01:13:53.719491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142957a40c0b'
down_revision = '64aa2e5f0745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apelido', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apelido')
    # ### end Alembic commands ###
