"""empty message

Revision ID: 87d96f151436
Revises: 5416d59c829d
Create Date: 2022-09-15 01:14:53.050360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d96f151436'
down_revision = '5416d59c829d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apelido', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apelido')
    # ### end Alembic commands ###
